# Generated by Django 5.2 on 2026-07-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userappprofile',
            name='user_app_pr_app_nam_6943a7_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='userappprofile',
            name='app_user_id',
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='login_type',
            field=models.CharField(choices=[('phone_code', '手机验证码'), ('username_password', '账号密码')], max_length=20, verbose_name='登录方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddIndex(
            model_name='userappprofile',
            index=models.Index(fields=['app_name', 'is_active'], name='user_app_pr_app_nam_576f9c_idx'),
        ),
    ]
