# Generated by Django 5.2 on 2026-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userappprofile_user_app_pr_app_nam_6943a7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='验证码'),
        ),
    ]
