# Generated by Django 5.2 on 2026-07-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_verificationcode_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
