# Generated by Django 5.2 on 2025-04-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('url', models.URLField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
