# Generated by Django 5.2 on 2026-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, verbose_name='微信OpenID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='状态')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('url', models.URLField(verbose_name='图片URL')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '图片转换记录',
                'verbose_name_plural': '图片转换记录',
                'db_table': 'image_conversion_records',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='结果')),
            ],
            options={
                'verbose_name': '任务结果',
                'verbose_name_plural': '任务结果',
                'db_table': 'task_results',
            },
        ),
    ]
