# Generated by Django 5.2 on 2025-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0002_taskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconversionrecord',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='imageconversionrecord',
            name='task_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
