# Generated by Django 5.2 on 2026-07-18 16:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('system', '系统通知'), ('topic_reply', '话题回复'), ('topic_like', '话题点赞'), ('verification', '认证通知'), ('invitation', '邀请通知')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('related_id', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用通知',
                'verbose_name_plural': '应用通知',
                'db_table': 'neighbor_hub_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='小区名称')),
                ('address', models.CharField(max_length=255, verbose_name='小区地址')),
                ('description', models.TextField(blank=True, verbose_name='小区描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('established_at', models.DateField(blank=True, null=True, verbose_name='建成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '小区',
                'verbose_name_plural': '小区',
                'db_table': 'neighbor_hub_communities',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_phone', models.CharField(max_length=20)),
                ('invitee_name', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='neighbor_hub.community')),
            ],
            options={
                'verbose_name': '邀请记录',
                'verbose_name_plural': '邀请记录',
                'db_table': 'neighbor_hub_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeighborHubProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业'), ('unverified', '待认证')], default='unverified', max_length=20, verbose_name='角色')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='楼号')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='个人简介')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已认证')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='neighbor_hub.community', verbose_name='所属小区')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_hub_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邻里圈用户档案',
                'verbose_name_plural': '邻里圈用户档案',
                'db_table': 'neighbor_hub_profiles',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_building', models.CharField(max_length=50, verbose_name='作者楼号')),
                ('author_role', models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业'), ('unverified', '待认证')], max_length=20)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('facility', '设施改造'), ('notice', '物业通知'), ('neighbor', '邻里关系'), ('environment', '环境治理'), ('repair', '设施维修'), ('help', '邻里互助'), ('announcement', '业委会公告'), ('activity', '社区活动'), ('dispute', '邻里纠纷'), ('other', '其他')], default='other', max_length=20)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('poster_style', models.CharField(choices=[('gradient', '渐变'), ('emoji', '表情'), ('minimal', '简约')], default='minimal', max_length=10)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已结束'), ('pending', '待审核'), ('rejected', '已拒绝')], default='active', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='neighbor_hub.community')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'db_table': 'neighbor_hub_topics',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_building', models.CharField(max_length=50)),
                ('author_role', models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业'), ('unverified', '待认证')], max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='neighbor_hub.comment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='neighbor_hub.topic')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'neighbor_hub_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='neighbor_hub.community')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '认证申请',
                'verbose_name_plural': '认证申请',
                'db_table': 'neighbor_hub_verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='neighbor_hub.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '话题点赞',
                'verbose_name_plural': '话题点赞',
                'db_table': 'neighbor_hub_topic_likes',
                'unique_together': {('topic', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='neighbor_hub.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '话题订阅',
                'verbose_name_plural': '话题订阅',
                'db_table': 'neighbor_hub_topic_subscriptions',
                'unique_together': {('topic', 'user')},
            },
        ),
    ]
