# Generated by Django 5.2 on 2026-07-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhubprofile',
            options={'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee_phone',
        ),
        migrations.AddField(
            model_name='neighborhubprofile',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='neighborhubprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
    ]
