# Generated by Django 5.2 on 2026-07-22 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0002_alter_neighborhubprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsubscription',
            options={'ordering': ['-is_pinned', '-pinned_at', '-updated_at'], 'verbose_name': '话题订阅', 'verbose_name_plural': '话题订阅'},
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='个人置顶'),
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_role',
            field=models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborhubprofile',
            name='role',
            field=models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业')], default='owner', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author_role',
            field=models.CharField(choices=[('owner', '业主'), ('committee', '业委会'), ('property', '物业')], max_length=20),
        ),
        migrations.CreateModel(
            name='TopicReadRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_count', models.PositiveIntegerField(default=1, verbose_name='阅读次数')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最后阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='neighbor_hub.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '话题阅读',
                'verbose_name_plural': '话题阅读',
                'db_table': 'neighbor_hub_topic_read_records',
                'indexes': [models.Index(fields=['user', 'last_read_at'], name='neighbor_hu_user_id_056104_idx')],
                'unique_together': {('topic', 'user')},
            },
        ),
    ]
