# Generated by Django 5.2 on 2026-07-26 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0004_topicimage_topic_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-is_pinned', '-published_at'], 'verbose_name': '话题', 'verbose_name_plural': '话题'},
        ),
        migrations.AddField(
            model_name='topic',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='topicimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
