# Generated by Django 5.2 on 2026-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0005_add_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后编辑时间'),
        ),
    ]
