# Generated by Django 5.2 on 2026-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0006_update_timestamps_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('active', '正常'), ('closed', '已关闭'), ('hidden', '已隐藏')], default='active', max_length=20),
        ),
    ]
