# Generated by Django 5.2 on 2026-07-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0007_update_topic_status_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='community',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppNotification',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
