# Generated by Django 5.2 on 2026-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0008_remove_verificationrequest_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhubprofile',
            name='join_note',
            field=models.CharField(blank=True, default='', help_text='用户加入小区时填写的备注，供业委会审核参考', max_length=255, verbose_name='加入备注'),
        ),
    ]
