# Generated by Django 5.2 on 2026-07-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0009_add_join_note_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='回复的目标用户（扁平化回复模型：parent 指向根评论，reply_to 指向被回复的用户）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='回复给'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='回复的根评论（顶级评论），非回复时为 null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='neighbor_hub.comment', verbose_name='根评论'),
        ),
    ]
