# Generated by Django 5.2 on 2026-07-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_hub', '0011_add_commentlike_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='inviter_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='neighbor_hub.community', verbose_name='邀请人所属小区'),
        ),
    ]
